queue=[]
print('before enqueue,its empty')
print(queue)
queue=["A","B","C"]
print('after enqueue ,the quque is')
print(queue)
print('now enqueue or insertion')
queue.append("D")
queue.append("E")
print(queue)
print('after deletion,dequeue')
print(queue.pop(0))
print(queue)
print(queue.pop(0))
print(queue)
print(queue.pop(0))
print(queue)
print(queue.pop(0))
print(queue)
print(queue.pop(0))
print(queue)
print(queue.pop(0))
print(queue)
